#! /bin/bash
# If not running interactively, don't do anything
[[ "$-" != *i* ]] && return

### CONSTANTS ###
NORMAL="\e[0m"
WHITE="\e[0;37m"
WHITE_BOLD="\e[1;37m"
RED="\e[0;31m"
RED_BOLD="\e[1;31m"
GREEN="\e[0;32m"
GREEN_BOLD="\e[1;32m"
YELLOW="\e[0;33m"
YELLOW_BOLD="\e[1;33m"
BLUE="\e[0;34m"
BLUE_BOLD="\e[1;34m"
MAGENTA="\e[0;35m"
MAGENTA_BOLD="\e[1;35m"
CYAN="\e[0;36m"
CYAN_BOLD="\e[1;36m"

### FUNCTIONS ###
function pick_color() {
    if [[ $? = 0 ]]; then
	echo ":)" > /tmp/bash.face
	echo -e "\e[1;36m"
    else
	echo ":(" > /tmp/bash.face
	echo -e "\e[1;35m"
    fi
}

function get_face() {
    cat /tmp/bash.face
}

function parse_git_branch {
    git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

function busy() {
    cat /dev/urandom | hexdump -C | grep "ca fe"
}

function errcode() {
    perl -le 'print $!+0, "\t", $!++ for 0..127'
}

function extract {
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)  tar xjf $1      ;;
            *.tar.gz)   tar xzf $1      ;;
            *.bz2)      bunzip2 $1      ;;
            *.rar)      rar x $1        ;;
            *.gz)       gunzip $1       ;;
            *.tar)      tar xf $1       ;;
            *.tbz2)     tar xjf $1      ;;
            *.tgz)      tar xzf $1      ;;
            *.zip)      unzip $1        ;;
            *.Z)        uncompress $1   ;;
            *)          echo "'$1' cannot be extracted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

function cd {
    builtin cd "$@" && ls -l --color=auto
}

### EXPORT ###
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export TERM=xterm-256color
export PROMPT_DIRTRIM=3
export PS1="\\[$NORMAL\]\[\$(pick_color)\]\$(get_face)\[$BLUE_BOLD\][\A]\[$GREEN_BOLD\]\u:\[$RED_BOLD\]\w\[$YELLOW_BOLD\]\$(parse_git_branch)\[$WHITE_BOLD\] \\$ \[$NORMAL\]"
export HISTTIMEFORMAT="%F %T "
export PATH="~/.emacs.d/microcebus/bin:$PATH"
export LD_LIBRARY_PATH="$HOME/.emacs.d/microcebus/lib:$LD_LIBRARY_PATH"
export PYTHONSTARTUP=~/.pythonrc
export CDPATH=/etc:$CDPATH

### ALIAS ###
alias grep='grep --color=auto --line-buffered'
alias ll='ls -lh --color=auto'
alias ec='emacs -nw'
alias dirs='dirs -v'
alias gcc='gcc -g -rdynamic -L$HOME/.emacs.d/microcebus/lib -lpthread -lmicrocebus `pkg-config --cflags --libs glib-2.0`'
alias cde='cd ~/.emacs.d'
alias cdk='/lib/modules/$(uname -r)/kernel'
alias j='jobs -l'
alias ag='ag -f -u -t --depth -1'
alias ..='cd ..'
alias .2='cd ../..'
alias ...='.2'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'
# alias diff='diff -Naur'
# alias patch='patch -b'

if [[ -n $DISPLAY ]]; then
    # Load the user's own X resource settings
    [[ -r $HOME/.Xresources ]] && xrdb $HOME/.Xresources
fi





## .inputrc

## C-x C-r command re-reads this init file
## shell-expand-line (M-C-e)

## "\C-p": history-search-backward
## "\C-n": history-search-forward
## "\e\C-h": unix-word-rubout
## "\e\C-?": unix-word-rubout
