(elpy-enable)
(add-hook 'elpy-mode-hook
          (lambda ()
            ;; (setq indent-tabs-mode nil)
            ;; (setq tab-width 4)
            ;; (setq python-indent 4)
            (define-key elpy-mode-map (kbd "M-.") 'elpy-goto-definition)
            (define-key elpy-mode-map (kbd "C-x M-.") 'elpy-goto-definition-other-window)
            (define-key elpy-mode-map (kbd "M-,") 'pop-tag-mark)
            (define-key elpy-mode-map (kbd "M-RET") 'elpy-company-backend)
            (highlight-indentation-mode -1)
            ))